### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by cdeil** [denisleahy/SNRmodels#1]
@robertazanin pointed out your paper to me just now.
@denisleahy - Thanks for sharing your code!

In Gammapy we have something very primitive to model SNRs and SNR populations (see [here](http://docs.gammapy.org/en/latest/astro/source/snr.html)). We'll add a link to your paper and code.

Could you please add a license?

The reason I'm asking is that as Jake says (see [here](https://twitter.com/jakevdp/status/757985928501600256) or [here](http://www.astrobetter.com/blog/2014/03/10/the-whys-and-hows-of-licensing-scientific-code/)
> if you publish code without a license, it defaults to "all rights reserved" & makes it difficult for others to use & adapt

Technically it's simple, if you're willing to do it. You just copy a `LICENSE.txt` file into the repository and mention what license the project has in the README. Numpy, Scipy, Matplotlib and Astropy all use this one: https://opensource.org/licenses/BSD-3-Clause

**Comment by denisleahy** [comment]
Dear Christoph:

thanks for the info. I have added a license now. I will look at Gammapy and your code.

Denis.

________________________________

**Comment by cdeil** [comment]
> thanks for the info. I have added a license now. I will look at Gammapy and your code.

Thank you! Wonderful.
Now that you have a license, I can also look at your code.
:-)

I don't have the need for SNRs at the moment, but just to mention: I ran `python snr.py` to see if it works for me. It does! 😄  This is on Mac.
